// Shared types for the portal

// User roles and access control
export type UserRole = "Manager" | "Sales" | "Warehouse" | "Traffic" | "Operation" | "User"

export interface RoleAccessControl {
  role: UserRole
  allowedPages: string[]
}

export interface EventData {
  eventName: string // NEW: Event name/title
  eventDate: string
  dayOfWeek: string
  eventType: string
  eventTypeOther?: string
  customerPreferredSetupDate: string // RENAMED
  setupDayOfWeek: string
  customerPreferredDismantleDate: string // RENAMED
  dismantleDayOfWeek: string
  estimatedGuests: number
  budgetPerHead?: number
  dismantleRequired?: boolean
  areaType: "private" | "public" | "indoor" | "outdoor"
  areaSelection: string
  locationAreaType?: "etre-cafe" | "other"
  locationAreaOther?: string
  duration: number
  desiredSetupTime: string
  desiredDismantleTime: string
}

export interface PricingData {
  tent10x10: { quantity: number; color: string }
  tent20x20: { quantity: number; color: string }
  tent20x30: { quantity: number; color: string }
  tableSet: number
  longTable: { quantity: number; withSkirting: boolean }
  extraChairs: number
  coolerFan: number
  parkingLots: number
  transportationFee?: number
}

export interface CustomerData {
  customerName: string // NEW: Customer name
  companyName: string // NEW: Company name
  phone: string
  email: string
  // Billing address (legacy + new)
  billingBuildingName?: string
  billingAddressGate: string
  billingAddressJalan: string
  billingAddressTaman: string
  billingAddress1?: string
  billingAddress2?: string
  billingCity?: string
  billingAddress: string
  billingPostCode: string
  billingState: string
  // Delivery address (legacy + new)
  deliveryBuildingName?: string
  deliveryAddressGate: string
  deliveryAddressJalan: string
  deliveryAddressTaman: string
  deliveryAddress1?: string
  deliveryAddress2?: string
  deliveryCity?: string
  deliveryAddress: string
  deliveryPostCode: string
  deliveryState: string
  setupTimeSlot: string
  dismantleTimeSlot: string
  setupTimeWindowMode?: "strict" | "flexible" // Time flexibility for setup
  dismantleTimeWindowMode?: "strict" | "flexible" // Time flexibility for dismantle
  specialRequest: string
  photos: string[]
}

export interface OrderItem {
  inventoryId?: string
  name: string
  description?: string
  quantity: number | string
  unitPrice: number
  sst: number
  total: number
  sstApplied?: boolean
  setupMinsPerUnit?: number
  dismantleMinsPerUnit?: number
}

export interface OrderMeta {
  orderNumber: string
  orderDate: string
  orderTime: string
  madeBy: string
  position: string
  isAutoGenerated: boolean
  salesOrderNumber?: string
}

export interface AdditionalInfo {
  setupDepartureFromType: "hub" | "other" | ""
  setupDepartureAddress: string
  setupDestinationAddress: string
  setupDistanceKm: number // Distance in km for setup journey
  departureFromHub: string // time HH:MM
  travelDurationHours: number
  travelDurationMinutes: number
  setupDurationHours: number
  setupDurationMinutes: number
  scheduleStartTime: string
  // Legacy/optimizer fields (optional)
  setupArrivalTime?: string
  setupDepartureTime?: string
  setupWorkMins?: number
  setupLorry: "Team A" | "Team B" | "Team C" | "Team D" | "Team E" | ""
  tentSetupTimeCalculated: number // auto-calculated based on tent quantity
  dismantleWorkTimeCalculated?: number // auto-calculated per inventory durations (optional, backward compatible)
  bufferTime: string // minutes as string
  bufferReason: string
  totalTaskTimeHours: number
  totalTaskTimeMinutes: number
  estimatedEndTime: string
  // Journey after setup completion (Traffic Return)
  setupNextAction: "warehouse" | "next-task" | "" // Legacy - kept for backward compatibility
  setupReturnChoice: "return-to-hub" | "remain-on-site" | ""
  setupReturnFromType: "site" | "other" | ""
  setupReturnFromAddress: string
  setupReturnDepartureTime: string // HH:MM when leaving site
  setupReturnTravelHours: number
  setupReturnTravelMinutes: number
  setupReturnDistanceKm: number
  setupReturnToType: "hub" | "other" | ""
  setupReturnToAddress: string
  setupReturnTravelMins: number // Legacy - kept for backward compatibility
  setupReturnArrivalTime: string // Time arriving back at hub or next location
  setupNextTaskOrderNumber: string // If going to next task, which order
  // Confirmed times by personnel
  confirmedSetupDate: string // NEW: Personnel confirmed setup date
  confirmedSetupTime: string // NEW: Personnel confirmed setup time
  confirmedDismantleDate: string // NEW: Personnel confirmed dismantle date
  confirmedDismantleTime: string // NEW: Personnel confirmed dismantle time
  // Dismantle planning
  dismantleDepartureFromType: "hub" | "other" | ""
  dismantleDepartureAddress: string
  dismantleDestinationAddress: string
  dismantleDistanceKm: number // Distance in km for dismantle journey
  dismantleDepartureTime: string
  dismantleTravelHours: number
  dismantleTravelMinutes: number
  dismantleDurationHours: number
  dismantleDurationMinutes: number
  dismantleScheduleStartTime: string
  // Legacy/optimizer fields (optional)
  dismantleArrivalTime?: string
  dismantleWorkMins?: number
  dismantleLorry: "Team A" | "Team B" | "Team C" | "Team D" | "Team E" | ""
  dismantleBufferTime: string
  dismantleBufferReason: string
  dismantleTotalTimeHours: number
  dismantleTotalTimeMinutes: number
  dismantleEstimatedEndTime: string
  // Journey after dismantle completion (Traffic Return)
  dismantleNextAction: "warehouse" | "next-task" | "" // Legacy - kept for backward compatibility
  dismantleReturnChoice: "return-to-hub" | "remain-on-site" | ""
  dismantleReturnFromType: "site" | "other" | ""
  dismantleReturnFromAddress: string
  dismantleReturnDepartureTime: string // HH:MM when leaving site
  dismantleReturnTravelHours: number
  dismantleReturnTravelMinutes: number
  dismantleReturnDistanceKm: number
  dismantleReturnToType: "hub" | "other" | ""
  dismantleReturnToAddress: string
  dismantleReturnTravelMins: number // Legacy - kept for backward compatibility
  dismantleReturnArrivalTime: string // Time arriving back at hub or next location
  dismantleNextTaskOrderNumber: string // If going to next task, which order
  // Other adhoc planning (for ad-hoc orders that require Other Adhoc)
  confirmedOtherAdhocDate: string
  confirmedOtherAdhocTime: string
  otherAdhocDurationHours: number
  otherAdhocDurationMinutes: number
  otherAdhocScheduleStartTime: string
  // Legacy/optimizer fields (optional)
  otherAdhocArrivalTime?: string
  otherAdhocDepartureTime?: string
  otherAdhocWorkMins?: number
  otherAdhocLorry: "Team A" | "Team B" | "Team C" | "Team D" | "Team E" | ""
  otherAdhocBufferTime: string
  otherAdhocBufferReason: string
  otherAdhocTotalTimeHours: number
  otherAdhocTotalTimeMinutes: number
  otherAdhocEstimatedEndTime: string
  // Personnel info
  schedulingPersonnel: string
  schedulingDate: string
  schedulingTime: string
}

export interface PackingData {
  items: PackingItem[]
  packingPersonnel: string
  packingDate: string
  packingTime: string
  status: "pending" | "packed" | "rejected"
}

export interface PackingItem {
  name: string
  quantity: number | string
  packed: boolean
}

// GPS Tracking Types
export interface GPSPoint {
  latitude: number
  longitude: number
  timestamp: string
  accuracy?: number
  streetName?: string
  fullAddress?: string
}

export interface GPSTrackingData {
  startLocation: GPSPoint | null
  endLocation: GPSPoint | null
  route: GPSPoint[]
  startedAt: string | null
  endedAt: string | null
}

export interface SetupAcceptance {
  personnel: string
  acceptedDate: string
  acceptedTime: string
  lorry: string
}

export interface JourneyStart {
  personnel: string
  date: string
  time: string
  startLocation: GPSPoint
}

export type SetupPhase = "pending" | "accepted" | "tracking" | "photos_saved" | "completed"

export interface SetupData {
  setupPersonnel: string
  setupDate: string
  setupStartTime: string
  setupCompletionTime: string
  photos: string[]
  status: "pending" | "completed" | "rejected"
  // New GPS tracking fields
  phase?: SetupPhase
  acceptance?: SetupAcceptance
  journeyStart?: JourneyStart
  gpsTracking?: GPSTrackingData
  photosSavedAt?: string
}

export type DismantlePhase = "pending" | "accepted" | "tracking" | "photos_saved" | "completed"

export interface DismantleAcceptance {
  personnel: string
  acceptedDate: string
  acceptedTime: string
  lorry: string
}

export interface DismantleData {
  dismantlePersonnel: string
  dismantleDate: string
  dismantleStartTime: string
  dismantleCompletionTime: string
  photos: string[]
  status: "pending" | "completed" | "rejected"
  // New GPS tracking fields (same as SetupData)
  phase?: DismantlePhase
  acceptance?: DismantleAcceptance
  journeyStart?: JourneyStart
  gpsTracking?: GPSTrackingData
  photosSavedAt?: string
}

export interface OtherAdhocData {
  personnel: string
  date: string
  time: string
  status: "pending" | "completed" | "rejected"
}

export type OrderStatus = 
  | "draft" 
  | "scheduling" 
  | "packing" 
  | "procurement"
  | "setting-up" 
  | "dismantling" 
  | "other-adhoc"
  | "completed" 
  | "cancelled"

export interface MaterialPlanningLine {
  category: string
  item: string
  quantity: string
  picName: string
  purchasingRequired: boolean
  adequacy: "enough" | "inadequate" | "unknown"
}

export interface MaterialPlanningData {
  lines: MaterialPlanningLine[]
  updatedAt: string
  confirmedBy?: string
}

export interface QuotationOptions {
  brandingRequirement: {
    type: "none" | "logo" | "colour"
    logoOn: {
      dessert: boolean
      packaging: boolean
      other: string
    }
    colourOn: {
      dessert: boolean
      packaging: boolean
      other: string
    }
  }
  preferredMenuSelection: {
    step1: "current" | "partial" | "full"
    notes: string
    size: "normal" | "mini"
    drinks: {
      coffee: boolean
      tea: boolean
      fizzy: boolean
      other: string
    }
    packagingBox: "customer-own" | "etre-existing" | "premium"
    dietaryNeeds: string
    servingStyle: {
      individualDessertBox: boolean
      buffetCateringStyle: boolean
    }
  }
}

export interface IssueData {
  flaggedPersonnel: string
  flaggedIssue: string
  flaggedDate: string
  flaggedTime: string
  flaggedAtStage: OrderStatus
  isResolved: boolean
  resolvedNote?: string
  resolvedDate?: string
  resolvedTime?: string
  resolvedBy?: string
}

export interface SalesOrder {
  id: string
  orderNumber: string
  orderMeta: OrderMeta
  orderSource?: "sales" | "ad-hoc"
  adHocOptions?: {
    requiresPacking: boolean
    requiresSetup: boolean
    requiresDismantle: boolean
    requiresOtherAdhoc: boolean
    requiresJourney?: boolean // For Other Adhoc journey tracking
    requiresGPSTracking?: boolean // NEW: GPS tracking requirement for ad-hoc
    otherAdhocName?: string
  }
  salesOrderDate: string
  expirationDate: string
  status: OrderStatus
  hasIssue: boolean // Flag for problematic/issue spot
  issueData?: IssueData // Issue tracking data
  eventData: EventData
  pricingData: PricingData
  customerData: CustomerData
  items: OrderItem[]
  subtotal: number
  tax: number
  discount: number
  discountType: "amount" | "percentage"
  discountAppliesTo: "subtotal" | "total" // NEW: Whether discount is before or after SST
  total: number
  additionalInfo?: AdditionalInfo
  packingData?: PackingData
  materialPlanning?: MaterialPlanningData
  quotationOptions?: QuotationOptions
  setupData?: SetupData
  dismantleData?: DismantleData
  otherAdhocData?: OtherAdhocData
  createdAt: string
  updatedAt: string
}

// Pricing constants
export const PRICES = {
  tent10x10: 220,
  tent20x20: 250,
  tent20x30: 300,
  tableSet: 100,
  longTable: 15,
  longTableWithSkirting: 30,
  extraChairs: 5,
  coolerFan: 200,
  mbiPermit: 20,
  mbiParking: 10,
  runnerFee: 100,
  sundayOT: 300,
  durationExtension: 300,
}

export const SST_RATE = 0.08

export const TENT_CAPACITY = {
  "10x10": 20,
  "20x20": 50,
  "20x30": 70,
}

export const TABLE_SET_CAPACITY = 10

export const TIME_SLOTS = [
  "8:00am - 9:00am",
  "9:00am - 10:00am",
  "10:00am - 11:00am",
  "11:00am - 12:00pm",
  "12:00pm - 1:00pm",
  "1:00pm - 2:00pm",
  "2:00pm - 3:00pm",
  "3:00pm - 4:30pm",
]

export const MALAYSIAN_STATES = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Perak",
  "Perlis",
  "Penang",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
  "Kuala Lumpur",
  "Labuan",
  "Putrajaya",
]

export const POSITIONS = [
  "Sales Admin",
  "Sales",
  "Warehouse",
  "Traffic",
  "Operation",
  "Manager",
]

export const LORRIES = [
  { id: "lorry-a", name: "Team A", color: "#FF6B6B" },
  { id: "lorry-b", name: "Team B", color: "#4ECDC4" },
  { id: "lorry-c", name: "Team C", color: "#FFE66D" },
  { id: "lorry-d", name: "Team D", color: "#95E1D3" },
  { id: "lorry-e", name: "Team E", color: "#DDA0DD" },
] as const

// Setup time per tent in minutes
export const SETUP_TIMES = {
  tent10x10: 30,
  tent20x20: 35,
  tent20x30: 40,
}

export const BUFFER_TIME_OPTIONS = [
  { value: "15", label: "15 mins" },
  { value: "30", label: "30 mins" },
  { value: "45", label: "45 mins" },
  { value: "60", label: "1 hour" },
  { value: "75", label: "1 hour 15 mins" },
  { value: "90", label: "1 hour 30 mins" },
  { value: "105", label: "1 hour 45 mins" },
  { value: "120", label: "2 hours" },
]

export const DEFAULT_BUFFER_TIME = "30"

// Workflow phases with navigation paths
export function getPhaseIndex(status: OrderStatus): number {
  switch (status) {
    case "draft": return 0
    case "scheduling": return 1
    case "packing": return 2
    case "procurement": return 3
    case "setting-up": return 4
    case "dismantling": return 5
    case "other-adhoc": return 6
    case "completed": return 7
    case "cancelled": return -1
    default: return 0
  }
}

export function getPhaseFromPath(pathname: string): number {
  if (pathname.includes("sales-order")) return 0
  if (pathname.includes("ad-hoc")) return 0
  if (pathname.includes("scheduling")) return 1
  if (pathname.includes("packing")) return 2
  if (pathname.includes("procurement")) return 3
  if (pathname.includes("setting-up")) return 4
  if (pathname.includes("dismantle")) return 5
  if (pathname.includes("other-adhoc")) return 6
  if (pathname.includes("completed")) return 7
  return 0
}

// Calculate tent setup time based on quantities
export function calculateTentSetupTime(pricingData: PricingData): number {
  const tent10x10Time = pricingData.tent10x10.quantity * SETUP_TIMES.tent10x10
  const tent20x20Time = pricingData.tent20x20.quantity * SETUP_TIMES.tent20x20
  const tent20x30Time = pricingData.tent20x30.quantity * SETUP_TIMES.tent20x30
  return tent10x10Time + tent20x20Time + tent20x30Time
}

export function parseOrderItemQuantity(value: number | string): number {
  const n = typeof value === "string" ? Number.parseFloat(value) : value
  return Number.isFinite(n) ? Math.max(0, n) : 0
}

export function calculateWorkMinutesFromItems(items: OrderItem[] | undefined, kind: "setup" | "dismantle"): number {
  if (!items || !Array.isArray(items) || items.length === 0) return 0
  return items.reduce((sum, item) => {
    const qty = parseOrderItemQuantity(item.quantity)
    if (qty <= 0) return sum
    const perUnit =
      kind === "setup"
        ? (typeof item.setupMinsPerUnit === "number" ? item.setupMinsPerUnit : 0)
        : (typeof item.dismantleMinsPerUnit === "number"
            ? item.dismantleMinsPerUnit
            : (typeof item.setupMinsPerUnit === "number" ? item.setupMinsPerUnit : 0))
    const mins = Number.isFinite(perUnit) ? Math.max(0, perUnit) : 0
    return sum + qty * mins
  }, 0)
}

// Check if customer preferred and confirmed times are inconsistent
export function hasTimeInconsistency(order: SalesOrder): boolean {
  if (!order.additionalInfo) return false
  
  const ai = order.additionalInfo
  const ed = order.eventData
  
  const setupDateMismatch = Boolean(ai.confirmedSetupDate && ai.confirmedSetupDate !== ed.customerPreferredSetupDate)
  const setupTimeMismatch = Boolean(ai.confirmedSetupTime && ai.confirmedSetupTime !== ed.desiredSetupTime)
  const dismantleDateMismatch = Boolean(ai.confirmedDismantleDate && ai.confirmedDismantleDate !== ed.customerPreferredDismantleDate)
  const dismantleTimeMismatch = Boolean(ai.confirmedDismantleTime && ai.confirmedDismantleTime !== ed.desiredDismantleTime)
  
  return setupDateMismatch || setupTimeMismatch || dismantleDateMismatch || dismantleTimeMismatch
}
